Add swiftlint validation to swiftlintcheck

diff --git a/executables/swiftlintcheck b/executables/swiftlintcheck
--- a/executables/swiftlintcheck
+++ b/executables/swiftlintcheck
@@ -5,6 +5,13 @@
 # yellow light means that swiftlint --fix will autocorrect it. The rule type
 # shows to the right. Happy configuring!
 
+# Validate swiftlint install
+which swiftlint &> /dev/null
+[[ $? = 0 ]] || {
+	echo "\033[32mswiftlint\033[0m not found"
+	exit 1
+}
+
 # Validate argument
 [[ $1 = "" ]] && {
 	echo "Please supply a swiftlint config file."
